### ISSUE TITLE
Cassandra Exporter 

### ISSUE THREAD

**Issue by subinmt** [MySocialApp/kubernetes-helm-chart-cassandra#3]
Hi,

I am new to this cassandra_exporter. I have a Cassandra in my Kubernetes cluster. Now I am planning to fetch the Cassandra logs to Prometheus. I have tried to deployed ../kubernetes/templates/ yaml's. But we are getting many error like, missing of api versio, and unknown '{','}' and etc. Can you please let me know, how can I fetch my cassandra logs to Prometheus.
Regards,
Subin

**Comment by deimosfr** [comment]
Hi,

Cassandra Exporter is for metrics, not logs. If you have specific questions on Cassandra exporter, please refer directly to the Github project https://github.com/criteo/cassandra_exporter

If you have questions on the deployment, please add more info (logs etc...)
