### ISSUE TITLE
Install multiple release in same namespace

### ISSUE THREAD

**Issue by Vince-Cercury** [MySocialApp/kubernetes-helm-chart-cassandra#4]
In other charts I found that it's generally a convention to use the release name in the resource name. Example:

my-release-cassandra-0

So that we can have multiple installations in the same namespace. 

my-releaseX-cassandra-0
my-releaseY-cassandra-0

I've been trying to make that work by editing the templates and using kubernetes.fullname in resource names. Example:

```apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
```

I  had to edit the name in statefulset and edit the configmap to replace `kubernetes.name` with `kubernetes.fullname` as well as the service selector. But my pod can't reach the seed, so I must be doing something wrong

Is there a recommended way to use this chart so that it is not dependent on being installed in a new namespace? It would be very useful

I would prefer not to have to alter the templates like I did if possible

**Comment by deimosfr** [comment]
Hi,

Good question ! Never tested this yet. I think you're doing it right. Can you test with one google image ? gcr.io/google-samples/cassandra:v14

Thanks

**Comment by Vince-Cercury** [comment]
we have used the field to override the kubernetes.name

However, unlike other charts, if we don't specify that field  nor the release name, the release name is not used to generate the resources.

Closing this for now as override the kubernetes.name sort of does what we need, even though it does not follow conventions around using the release name
